version: "3.1"

# Configuration for Rasa NLU and Core
language: en

pipeline:
  # This is a basic pipeline that works well for most chatbots
- name: WhitespaceTokenizer      # Splits text into words
- name: RegexFeaturizer          # Extracts features based on regex patterns
- name: LexicalSyntacticFeaturizer    # Adds token-level features
- name: CountVectorsFeaturizer   # Vector representation of text using word counts
- name: DIETClassifier           # Entity extraction & intent classification
  epochs: 100
- name: EntitySynonymMapper      # Maps synonyms for consistent entity recognition
- name: ResponseSelector         # Matches user input with response variations
  epochs: 100
- name: FallbackClassifier       # Classifier for triggering fallback action
  threshold: 0.3                 # If confidence < 0.3, triggers fallback action

policies:
  # Rule-based policy to handle predictable conversation paths and fallback scenarios
- name: RulePolicy
  core_fallback_threshold: 0.3
  core_fallback_action_name: "action_default_fallback"
  enable_fallback_prediction: true

  # Memoization policy for remembering exact user conversations
- name: MemoizationPolicy
  max_history: 5                 # Remembers the last 5 turns to repeat common flows

  # Policy to handle conversations with unpredictable turns
- name: TEDPolicy
  max_history: 5
  epochs: 100                    # Number of epochs to train conversation policy
assistant_id: 20241104-222308-soft-gun
