version: "3.1"

# Configuration for Rasa NLU and Core
language: en

pipeline:
  # This is a basic pipeline that works well for most chatbots
- name: WhitespaceTokenizer         # Splits text into words
- name: RegexFeaturizer             # Extracts features based on regex patterns
- name: LexicalSyntacticFeaturizer   # Adds token-level features like prefixes, suffixes, etc.
- name: CountVectorsFeaturizer      # Vector representation of text using word counts
- name: DIETClassifier              # Entity extraction & intent classification
  epochs: 100                       # Adjusted number of epochs for better performance
  random_seed: 42                   # Added for reproducibility
- name: EntitySynonymMapper         # Maps synonyms for consistent entity recognition
- name: ResponseSelector            # Matches user input with predefined responses
  epochs: 100                       # Number of epochs for training ResponseSelector
- name: FallbackClassifier          # Classifier to trigger fallback action for uncertain queries
  threshold: 0.3                    # Threshold confidence level below which fallback is triggered

policies:
  # Rule-based policy to handle predictable conversation paths and fallback scenarios
- name: RulePolicy
  core_fallback_threshold: 0.3
  core_fallback_action_name: "action_default_fallback"
  enable_fallback_prediction: true

  # Memoization policy for remembering exact user conversations
- name: MemoizationPolicy
  max_history: 5                   # Remembers the last 5 turns to repeat common flows

  # Policy to handle conversations with unpredictable turns
- name: TEDPolicy
  max_history: 5
  epochs: 100                      # Number of epochs to train conversation policy
  random_seed: 42                  # Added for reproducibility
assistant_id: 20241105-003431-clever-demon
